services:
  db:
    image: pgvector/pgvector:pg16
    container_name: calibre-ai-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-calibre_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_calibre_2024}
      POSTGRES_DB: ${POSTGRES_DB:-calibre_ai_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data: